version: '3.8'

services:

  database:
    image: mysql:8.2.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  editor:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080 
    environment:
      ADMINER_DESIGN: hydra
    restart: always